function formato() {
    document.getElementById("info").innerHTML = "<h1>R</h1>"
    +"<center>"
    +"<form action='registro' style='width: 300px;'>"
        +"<fieldset class='borde3'>"
        +"<legend>rellena tus datos</legend>"
        +"<h1>rellena tus datos</h1>"
        +"<label for=''>tipo de documento</label>"
        +"<select name='' id=''>"
        +"<option value=''>tipo de documento</option>"
        +"<option value=''>targeta de identificacion</option>"
        +"<option value=''>cedula de ciudadania</option>"
        +"<option value=''>cedula de extrangeria</option>"
        +"</select> <br>"
        +"<label for=''>numero de documento</label> <br>"
        +"<input type='text' name='' id='fname' value='' placeholder='numero de documento'> <br>"
        +"<label for='nombres'>nombres</label> <br>"
        +"<input type='text' name='fname' id='fname' value='' placeholder='nombres'> <br>"
        +"<label for='apellidos'>apellidos</label> <br>"
        +"<input type='text' name='fname' id='fname' value='' placeholder='apellidos' > <br>"
        +"<label for='N°celular'>N°celular</label> <br>"
        +"<input type='text' name='fname' id='fname' value='' placeholder='N°celular'> <br>"
        +"<label for='password'>contraseña</label> <br>"
        +"<input type='password' name='password' id='fname' value='' placeholder='contaseña'> <br>"
        +"<label for='password'>confirmar contraseña</label> <br>"
        +"<input type='password' name='password' id='fname' value='' placeholder=''> <br>"
        +"<button type='ingresar' onclick='alert ('por favor ingresa')'><a href=''>ingresar</a></button>"
        +"<button type='guardar' onclick='alert ('usuario registrado')'><a href=''>guardar</a></button>"
    +"</fieldset>"
    +"</form>"
    +"</center>";
}
function formato() {
    document.getElementById("info2").innerHTML = "<h1>R</h1>"
    *"<form action='registro' style='width: 300px;'>"
    +"<fieldset class='borde4'>"
    +"<legend>reguistra tu carro</legend>"
    +"<label for=''>tipo de carro</label> <br>"
    +"<select name='' id=''>"
        +"<option value=''>tipo de carro</option>"
        +"<option value=''>sedan</option>"
        +"<option value=''>camioneta SUV</option>"
        +"<option value=''>pic kup</option>"
    +"</select> <br>"
    +"<label for=''>modelo del carro</label> <br>"
    +"<input type='text' name='' id='fname' value='' placeholder='modelo del carro'> <br>"
    +"<label for='nombres'>placa del carro</label> <br>"
    +"<input type='text' name='fname' id='fname' value='' placeholder='placa del carro'> <br>"
    +"<label for='apellidos'>tipo de servicio</label> <br>"
    +"<select name='' id=''>"
        +"<option value=''>tipo de servicio</option>"
        +"<option value=''>cambio de aceite</option>"
        +"<option value=''>alineacion</option>"
        +"<option value=''>lavado</option>"
        +"<option value=''>sincronisacion</option>"
    +"</select> <br>" 
    +"<button type='ingresar' onclick='alert ('por favor ingresa') '><a href=''>cancelar</a></button>"
    +"<button type='guardar' onclick='alert ('usuario registrado') '><a href=''>guardar</a></button>"
+"</fieldset>"
+"</form>";
}